name: Check Pull-request

on: pull_request

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration release

      - name: Test
        run: dotnet test --no-build --configuration release --logger "trx;LogFileName=test-results.trx"

      - name: Upload test-results
        uses: actions/upload-artifact@v2
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: '**/test-results.trx'